window.SJ_INVENTORY = {
  "generatedFrom": "SJ inventory grouped by kit combo and color variants - 2020 folder photos matched.xlsx",
  "poster": "assets/seasonal-sale-poster.png",
  "discountRange": "50%-80%",
  "totalProducts": 59,
  "totalQuantity": 371,
  "missingImages": 7,
  "finishGuide": {
    "E23": "Glossy White",
    "E12": "Slate Gray",
    "E19": "Graphite",
    "E90": "Sabbia Beige",
    "E75": "Sable Elm",
    "E56": "American Walnut",
    "E40": "Bristol Beige",
    "E73": "Stone Gray",
    "F08": "Cinnamon",
    "F20": "Empire Gray",
    "F07": "Vintage Walnut",
    "F21": "Ocean Gray",
    "F13": "Cafe Walnut",
    "W01": "White",
    "H01": "Dark Cherry",
    "B02": "Black",
    "B01": "Black",
    "G47": "Glossy Empire Gray",
    "E01": "Blush Taupe",
    "BN": "Brushed Nickel",
    "CG": "Cool Gray",
    "BI": "Biscuit",
    "B1": "Biscuit",
    "WH": "White",
    "CW": "Carrara White"
  },
  "products": [
    {
      "row": 2,
      "code": "632012-1-H01",
      "name": "Drawer bank-Dark cherry",
      "finish": "Dark Cherry",
      "series": "Adina",
      "quantity": 25,
      "location": "R1A2: 20; R4A2: 5",
      "msrp": null,
      "salePrice": null,
      "discount": 70,
      "discountLabel": "70% off",
      "image": "assets/products/002-632012-1-h01.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder code match"
    },
    {
      "row": 3,
      "code": "015623-W01",
      "name": "23\" Adina Wall Mount Bathroom Vanity Base Cabinet in White",
      "finish": "White",
      "series": "Adina",
      "quantity": 4,
      "location": "R2A1: 4",
      "msrp": 458.0,
      "salePrice": 137.4,
      "discount": 70,
      "discountLabel": "70% off",
      "image": "assets/products/003-015623-w01.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder code match"
    },
    {
      "row": 6,
      "code": "034823-E23 Kit",
      "name": "Jenna/Ariella 23\" Vanity Kit - Glossy White",
      "finish": "Glossy White",
      "series": "Ariella/Jenna 23\" Glossy White",
      "quantity": 5,
      "location": "Cabinet 017823-E23: A2: 7; R2A3: 3 | Base 034823.07-E23: R4A1: 5",
      "msrp": 1723.0,
      "salePrice": 344.6,
      "discount": 80,
      "discountLabel": "80% off",
      "image": "assets/products/004-034823-07-e23.jpg",
      "hasPhoto": true,
      "sourceNote": "Kit card combines cabinet 017823-E23 with base 034823.07-E23.",
      "componentDetails": [
        {
          "label": "Cabinet",
          "code": "017823-E23",
          "quantity": 10,
          "location": "A2: 7; R2A3: 3"
        },
        {
          "label": "Base / legs",
          "code": "034823.07-E23",
          "quantity": 5,
          "location": "R4A1: 5"
        }
      ]
    },
    {
      "row": 5,
      "code": "034823-E12 Kit",
      "name": "Jenna 23\" Vanity Kit - Slate Gray",
      "finish": "Slate Gray",
      "series": "Jenna",
      "quantity": 15,
      "location": "Base 034823.07-E12: R1A2: 15",
      "msrp": null,
      "salePrice": null,
      "discount": 65,
      "discountLabel": "65% off",
      "image": null,
      "hasPhoto": false,
      "sourceNote": "Kit card for 034823-E12; listed component is base 034823.07-E12.",
      "componentDetails": [
        {
          "label": "Base / legs",
          "code": "034823.07-E12",
          "quantity": 15,
          "location": "R1A2: 15"
        },
        {
          "label": "Cabinet",
          "code": "034823-E12",
          "quantity": "not listed separately",
          "location": "verify showroom stock"
        }
      ]
    },
    {
      "row": 7,
      "code": "632512-E23",
      "name": "Drawer Bridge",
      "finish": "Glossy White",
      "series": "Ariella",
      "quantity": 8,
      "location": "A1: 4; R1A3: 3; R3A4: 1",
      "msrp": null,
      "salePrice": null,
      "discount": 70,
      "discountLabel": "70% off",
      "image": "assets/products/007-632512-e23.jpg",
      "hasPhoto": true,
      "sourceNote": "Same series high-res reference image"
    },
    {
      "row": 8,
      "code": "037036.06-BN",
      "name": "WLS36-BN Venus - Metal legs-Brushed Nickel",
      "finish": "Brushed Nickel",
      "series": "Bella/Venus",
      "quantity": 7,
      "location": "R2A2: 7",
      "msrp": null,
      "salePrice": null,
      "discount": 65,
      "discountLabel": "65% off",
      "image": "assets/products/008-037036-06-bn.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model high-res catalog image"
    },
    {
      "row": 9,
      "code": "037036.07-F08",
      "name": "WLS36-F08 Venus - 36\" Wood legs-Cinnamon",
      "finish": "Cinnamon",
      "series": "Bella/Venus",
      "quantity": 1,
      "location": "R2A2: 1",
      "msrp": null,
      "salePrice": null,
      "discount": 50,
      "discountLabel": "50% off",
      "image": "assets/products/009-037036-07-f08.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model high-res catalog image"
    },
    {
      "row": 10,
      "code": "037036.07-W01",
      "name": "Venus - 36\" Wood legs-White",
      "finish": "White",
      "series": "Bella/Venus",
      "quantity": 2,
      "location": "R4A1: 2",
      "msrp": null,
      "salePrice": null,
      "discount": 50,
      "discountLabel": "50% off",
      "image": "assets/products/010-037036-07-w01.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model high-res catalog image"
    },
    {
      "row": 11,
      "code": "037036.07-H01",
      "name": "WLS36-H01 Venus - 36\" Wood legs-Dark Cherry",
      "finish": "Dark Cherry",
      "series": "Bella/Venus 36\" Dark Cherry",
      "quantity": 4,
      "location": "R1A1: 3; R2A2: 1",
      "msrp": null,
      "salePrice": null,
      "discount": 60,
      "discountLabel": "60% off",
      "image": "assets/products/011-037036-07-h01.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model high-res catalog image"
    },
    {
      "row": 12,
      "code": "011236.00-L-H01",
      "name": "VBA36-H01 Bella/Venus - 36\" Wall mount/Contempo cabinet base - Dark Cherry",
      "finish": "Dark Cherry",
      "series": "Bella/Venus 36\" Dark Cherry",
      "quantity": 2,
      "location": "R2A1: 2",
      "msrp": null,
      "salePrice": null,
      "discount": 50,
      "discountLabel": "50% off",
      "image": "assets/products/012-011236-00-l-h01.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model high-res catalog image"
    },
    {
      "row": 13,
      "code": "011223.00-F08",
      "name": "VBA23-F08 Bella/Venus - 23\" Wall mount/Contempo cabinet base-Cinnamon",
      "finish": "Cinnamon",
      "series": "Bella/Venus",
      "quantity": 1,
      "location": "R2A1: 1",
      "msrp": 1530.0,
      "salePrice": 765.0,
      "discount": 50,
      "discountLabel": "50% off",
      "image": "assets/products/013-011223-00-f08.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model high-res catalog image"
    },
    {
      "row": 14,
      "code": "011223.00-H01",
      "name": "VBA23-H01 Bella/Venus - 23\" Wall mount/Contempo cabinet base-Dark Cherry",
      "finish": "Dark Cherry",
      "series": "Bella/Venus",
      "quantity": 16,
      "location": "A2: 6; R3A2: 10",
      "msrp": null,
      "salePrice": null,
      "discount": 70,
      "discountLabel": "70% off",
      "image": "assets/products/014-011223-00-h01.jpg",
      "hasPhoto": true,
      "sourceNote": "High-res catalog PDF image"
    },
    {
      "row": 15,
      "code": "011223.00-W01",
      "name": "Bella/Venus - 23\" Wall mount/Contempo cabinet base-White",
      "finish": "White",
      "series": "Bella/Venus",
      "quantity": 11,
      "location": "R2A1: 3; R2A2: 5; R4A3: 3",
      "msrp": 1530.0,
      "salePrice": 306.0,
      "discount": 80,
      "discountLabel": "80% off",
      "image": "assets/products/015-011223-00-w01.jpg",
      "hasPhoto": true,
      "sourceNote": "High-res old inventory image"
    },
    {
      "row": 16,
      "code": "632112-F08",
      "name": "12\" Drawer Bridge with Three Drawers in Cinnamon",
      "finish": "Cinnamon",
      "series": "Bella/Venus",
      "quantity": 9,
      "location": "A1: 4; R4A2: 5",
      "msrp": 998.0,
      "salePrice": 199.6,
      "discount": 80,
      "discountLabel": "80% off",
      "image": "assets/products/016-632112-f08.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model high-res catalog image"
    },
    {
      "row": 17,
      "code": "632112-H01",
      "name": "12\" Drawer Bridge with Three Drawers in Dark Cherry",
      "finish": "Dark Cherry",
      "series": "Bella/Venus",
      "quantity": 1,
      "location": "R4A2: 1",
      "msrp": 998.0,
      "salePrice": 449.1,
      "discount": 55,
      "discountLabel": "55% off",
      "image": "assets/products/017-632112-h01.jpg",
      "hasPhoto": true,
      "sourceNote": "High-res catalog PDF image"
    },
    {
      "row": 18,
      "code": "632115-F08",
      "name": "Drawer Bridge",
      "finish": "Cinnamon",
      "series": "Bella/Venus",
      "quantity": 9,
      "location": "R1A3: 5; R2A3: 1; R5A3: 3",
      "msrp": 1080.0,
      "salePrice": 216.0,
      "discount": 80,
      "discountLabel": "80% off",
      "image": "assets/products/018-632115-f08.jpg",
      "hasPhoto": true,
      "sourceNote": "Showroom photo supplied"
    },
    {
      "row": 19,
      "code": "050524-3-W01",
      "name": "24\" Briella Bathroom Vanity Cabinet Base with Flared Leg in White",
      "finish": "White",
      "series": "Briella",
      "quantity": 3,
      "location": "R2A3: 3",
      "msrp": null,
      "salePrice": null,
      "discount": 60,
      "discountLabel": "60% off",
      "image": "assets/products/019-050524-3-w01.jpg",
      "hasPhoto": true,
      "sourceNote": "High-res catalog PDF image"
    },
    {
      "row": 20,
      "code": "051724-3-W01",
      "name": "24\" Briella Bathroom Vanity Cabinet Base with Tapered Leg in White",
      "finish": "White",
      "series": "Briella",
      "quantity": 3,
      "location": "R3A4: 3",
      "msrp": null,
      "salePrice": null,
      "discount": 60,
      "discountLabel": "60% off",
      "image": "assets/products/020-051724-3-w01.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder exact match"
    },
    {
      "row": 21,
      "code": "036918-3-H01",
      "name": "18\" Cami Bathroom Vanity Base Cabinet with Wood Door in Dark Cherry",
      "finish": "Dark Cherry",
      "series": "Cami",
      "quantity": 5,
      "location": "R1A3: 3; R3A2: 2",
      "msrp": 712.0,
      "salePrice": 213.6,
      "discount": 70,
      "discountLabel": "70% off",
      "image": "assets/products/021-036918-3-h01.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder code match"
    },
    {
      "row": 22,
      "code": "018936.00-L-E12",
      "name": "36\" Chloe Bathroom Vanity Base Cabinet with Leg in Slate Gray - Large Drawer on Left",
      "finish": "Slate Gray",
      "series": "Chloe",
      "quantity": 6,
      "location": "R1A10: 3; R3A2: 3",
      "msrp": 1935.0,
      "salePrice": 483.75,
      "discount": 75,
      "discountLabel": "75% off",
      "image": "assets/products/022-018936-00-l-e12.jpg",
      "hasPhoto": true,
      "sourceNote": "High-res old inventory image Direction variant pricing aligned."
    },
    {
      "row": 23,
      "code": "018936.00-R-E12",
      "name": "36\" Chloe Bathroom Vanity Base Cabinet with Leg in Slate Gray - Large Drawer on Right",
      "finish": "Slate Gray",
      "series": "Chloe",
      "quantity": 5,
      "location": "R1A1: 3; R2A4: 2",
      "msrp": 1935.0,
      "salePrice": 483.75,
      "discount": 75,
      "discountLabel": "75% off",
      "image": "assets/products/023-018936-00-r-e12.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model high-res catalog image Direction variant pricing aligned. Image mirrored from 018936.00-L-E12."
    },
    {
      "row": 24,
      "code": "036036.07-E23",
      "name": "Chloe - 36\" legs w/open shelf-Glossy White",
      "finish": "Glossy White",
      "series": "Chloe",
      "quantity": 8,
      "location": "R3A3: 3; R3A4: 1; R4A1: 4",
      "msrp": null,
      "salePrice": null,
      "discount": 65,
      "discountLabel": "65% off",
      "image": "assets/products/024-036036-07-e23.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model high-res catalog image"
    },
    {
      "row": 25,
      "code": "066248-L-E75",
      "name": "48\" Genova Vanity in Sable Elm, Foors on Left",
      "finish": "Sable Elm",
      "series": "Genova",
      "quantity": 4,
      "location": "R3A1: 4",
      "msrp": null,
      "salePrice": null,
      "discount": 60,
      "discountLabel": "60% off",
      "image": "assets/products/025-066248-l-e75.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model high-res catalog image"
    },
    {
      "row": 26,
      "code": "066248-L-E12",
      "name": "Genova",
      "finish": "Slate Gray",
      "series": "Genova",
      "quantity": 4,
      "location": "R1A10: 4",
      "msrp": null,
      "salePrice": null,
      "discount": 60,
      "discountLabel": "60% off",
      "image": "assets/products/026-066248-l-e12.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model high-res catalog image"
    },
    {
      "row": 27,
      "code": "066248-L-W01",
      "name": "48\" Genova Vanity in White, Doors on Left",
      "finish": "White",
      "series": "Genova",
      "quantity": 3,
      "location": "R2A2: 1; R2A3: 2",
      "msrp": null,
      "salePrice": null,
      "discount": 60,
      "discountLabel": "60% off",
      "image": "assets/products/027-066248-l-w01.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model high-res catalog image"
    },
    {
      "row": 28,
      "code": "066230-E90",
      "name": "30\" Genova Vanity in Sabbia Beige",
      "finish": "Sabbia Beige",
      "series": "Genova",
      "quantity": 17,
      "location": "A2: 2; R1A1: 2; R1A4: 7; R2A4: 2; R3A1: 2; R4A3: 2",
      "msrp": null,
      "salePrice": null,
      "discount": 70,
      "discountLabel": "70% off",
      "image": "assets/products/028-066230-e90.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder code match"
    },
    {
      "row": 29,
      "code": "066236-L-E90",
      "name": "36\" Genova Vanity in Sabbia Beige-left sink",
      "finish": "Sabbia Beige",
      "series": "Genova",
      "quantity": 11,
      "location": "R1A4: 7; R4A3: 4",
      "msrp": null,
      "salePrice": null,
      "discount": 70,
      "discountLabel": "70% off",
      "image": "assets/products/029-066236-l-e90.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model photo from 2020 folder Direction variant pricing aligned."
    },
    {
      "row": 30,
      "code": "066236-R-E90",
      "name": "36\" Genova Vanity in Sabbia Beige, Doors on Right",
      "finish": "Sabbia Beige",
      "series": "Genova",
      "quantity": 3,
      "location": "R2A2: 1; R2A4: 2",
      "msrp": null,
      "salePrice": null,
      "discount": 70,
      "discountLabel": "70% off",
      "image": "assets/products/030-066236-r-e90.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model photo from 2020 folder Direction variant pricing aligned. Image mirrored from 066236-L-E90."
    },
    {
      "row": 31,
      "code": "051618-F07",
      "name": "18\" Juliet Bathroom Vanity Cabinet Base in Vintage Walnut",
      "finish": "Vintage Walnut",
      "series": "Juliet",
      "quantity": 6,
      "location": "R1A6: 6",
      "msrp": 1070.0,
      "salePrice": 267.5,
      "discount": 75,
      "discountLabel": "75% off",
      "image": "assets/products/031-051618-f07.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder code match"
    },
    {
      "row": 32,
      "code": "051618-W01",
      "name": "18\" Juliet Bathroom Vanity Cabinet Base in White",
      "finish": "White",
      "series": "Juliet",
      "quantity": 16,
      "location": "R1A6: 2; R2A1: 2; R3A2: 8; R4A1: 4",
      "msrp": 1070.0,
      "salePrice": 214.0,
      "discount": 80,
      "discountLabel": "80% off",
      "image": "assets/products/032-051618-w01.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder code match"
    },
    {
      "row": 33,
      "code": "052724-F20",
      "name": "24\" Newcastle Bathroom Vanity Cabinet Base in Empire Gray",
      "finish": "Empire Gray",
      "series": "Newcastle",
      "quantity": 4,
      "location": "R1A7: 4",
      "msrp": 1254.0,
      "salePrice": 376.2,
      "discount": 70,
      "discountLabel": "70% off",
      "image": "assets/products/033-052724-f20.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder exact match"
    },
    {
      "row": 34,
      "code": "052730-W01",
      "name": "30\" Newcastle Bathroom Vanity Cabinet Base in White",
      "finish": "White",
      "series": "Newcastle",
      "quantity": 4,
      "location": "R1A8: 4",
      "msrp": 1438.0,
      "salePrice": 431.4,
      "discount": 70,
      "discountLabel": "70% off",
      "image": "assets/products/034-052730-w01.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder code match"
    },
    {
      "row": 35,
      "code": "052736-W01",
      "name": "36\" Newcastle Bathroom Vanity Cabinet Base in White",
      "finish": "White",
      "series": "Newcastle",
      "quantity": 1,
      "location": "R2A4: 1",
      "msrp": 2179.0,
      "salePrice": 1089.5,
      "discount": 50,
      "discountLabel": "50% off",
      "image": "assets/products/035-052736-w01.jpg",
      "hasPhoto": true,
      "sourceNote": "High-res old inventory image"
    },
    {
      "row": 36,
      "code": "052748-F20",
      "name": "42\" Newcastle Bathroom Vanity Cabinet Base in Empire Gray",
      "finish": "Empire Gray",
      "series": "Newcastle",
      "quantity": 2,
      "location": "R3A4: 2",
      "msrp": 2984.0,
      "salePrice": 1193.6,
      "discount": 60,
      "discountLabel": "60% off",
      "image": "assets/products/036-052748-f20.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder code match"
    },
    {
      "row": 37,
      "code": "621115-3-W01",
      "name": "15\" Shaker Freestanding Bathroom Storage Drawer Bank in White",
      "finish": "White",
      "series": "Shaker",
      "quantity": 15,
      "location": "R2A4: 5; R5A2: 10",
      "msrp": 699.0,
      "salePrice": 139.8,
      "discount": 80,
      "discountLabel": "80% off",
      "image": "assets/products/037-621115-3-w01.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder exact match"
    },
    {
      "row": 38,
      "code": "621115-3-H01",
      "name": "Shaker",
      "finish": "Dark Cherry",
      "series": "Shaker",
      "quantity": 5,
      "location": "R1A8: 5",
      "msrp": 699.0,
      "salePrice": 209.7,
      "discount": 70,
      "discountLabel": "70% off",
      "image": "assets/products/038-621115-3-h01.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder code match"
    },
    {
      "row": 39,
      "code": "621112-3-W01",
      "name": "12\" Shaker Freestanding Bathroom Storage Drawer Bank in White",
      "finish": "White",
      "series": "Shaker",
      "quantity": 6,
      "location": "R4A1: 6",
      "msrp": 649.0,
      "salePrice": 129.8,
      "discount": 80,
      "discountLabel": "80% off",
      "image": "assets/products/039-621112-3-w01.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder code match"
    },
    {
      "row": 40,
      "code": "080824-3-H01",
      "name": "24\" Shaker Bathroom Vanity Cabinet Base with Wood Doors in Dark Cherry",
      "finish": "Dark Cherry",
      "series": "Shaker",
      "quantity": 3,
      "location": "R1A9: 3",
      "msrp": 919.0,
      "salePrice": 275.7,
      "discount": 70,
      "discountLabel": "70% off",
      "image": "assets/products/040-080824-3-h01.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder code match"
    },
    {
      "row": 41,
      "code": "080830-3-W01",
      "name": "30\" Shaker Bathroom Vanity Cabinet Base in White - Wood Doors",
      "finish": "White",
      "series": "Shaker",
      "quantity": 4,
      "location": "R1A7: 4",
      "msrp": 1034.0,
      "salePrice": 310.2,
      "discount": 70,
      "discountLabel": "70% off",
      "image": "assets/products/041-080830-3-w01.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder code match"
    },
    {
      "row": 42,
      "code": "200561-WH",
      "name": "Sink - Rectangle Undercounter Ceramic Vessel w/ Overflow White",
      "finish": "White",
      "series": "Shaker",
      "quantity": 34,
      "location": "R5A7: 34",
      "msrp": 343.0,
      "salePrice": 68.6,
      "discount": 80,
      "discountLabel": "80% off",
      "image": "assets/products/042-200561-wh.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder code match"
    },
    {
      "row": 43,
      "code": "081936-3L-W01",
      "name": "36\" shaker cabinet left sink white",
      "finish": "White",
      "series": "Shaker",
      "quantity": 4,
      "location": "R1A9: 4",
      "msrp": null,
      "salePrice": null,
      "discount": 65,
      "discountLabel": "65% off",
      "image": "assets/products/043-081936-3l-w01.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder exact match"
    },
    {
      "row": 44,
      "code": "E094142-E19",
      "name": "42\" Vento Bathroom Vanity - Graphite",
      "finish": "Graphite",
      "series": "Vento",
      "quantity": 1,
      "location": "R1A10: 1",
      "msrp": 2294.0,
      "salePrice": 1147.0,
      "discount": 50,
      "discountLabel": "50% off",
      "image": "assets/products/044-e094142-e19.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder code match"
    },
    {
      "row": 45,
      "code": "632213-F08",
      "name": "Drawer bridge",
      "finish": "Cinnamon",
      "series": "Devon",
      "quantity": 5,
      "location": "R3A4: 5",
      "msrp": 849.0,
      "salePrice": 212.25,
      "discount": 75,
      "discountLabel": "75% off",
      "image": "assets/products/045-632213-f08.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model high-res catalog image"
    },
    {
      "row": 46,
      "code": "E026117-E40",
      "name": "Brit - 71'' Tall Side Cabinet - Bristol Beige",
      "finish": "Bristol Beige",
      "series": "Brit",
      "quantity": 5,
      "location": "R1A5: 5",
      "msrp": 2064.0,
      "salePrice": 619.2,
      "discount": 70,
      "discountLabel": "70% off",
      "image": "assets/products/046-e026117-e40.jpg",
      "hasPhoto": true,
      "sourceNote": "Showroom photo supplied"
    },
    {
      "row": 47,
      "code": "E056124-W01",
      "name": "Marco - 49'' Tall & 23-5/8'' Width Side Cabinet - White",
      "finish": "White",
      "series": "Marco",
      "quantity": 1,
      "location": "R1A7: 1",
      "msrp": 1829.0,
      "salePrice": 914.5,
      "discount": 50,
      "discountLabel": "50% off",
      "image": null,
      "hasPhoto": false,
      "sourceNote": "No photo yet"
    },
    {
      "row": 48,
      "code": "E036117-E56",
      "name": "74\" Tall Noce Side Cabinet-Floor Standing - American Walnut",
      "finish": "American Walnut",
      "series": "Noce",
      "quantity": 4,
      "location": "R1A5: 4",
      "msrp": null,
      "salePrice": null,
      "discount": 55,
      "discountLabel": "55% off",
      "image": null,
      "hasPhoto": false,
      "sourceNote": "No photo yet"
    },
    {
      "row": 49,
      "code": "E016117-E73",
      "name": "Stack-71\" Tall Side Cabinet - Stone Gray",
      "finish": "Stone Gray",
      "series": "Stack",
      "quantity": 3,
      "location": "R1A5: 3",
      "msrp": 3329.0,
      "salePrice": 1165.15,
      "discount": 65,
      "discountLabel": "65% off",
      "image": null,
      "hasPhoto": false,
      "sourceNote": "No photo yet"
    },
    {
      "row": 50,
      "code": "216632-8-B1",
      "name": "32\" Evin™ Ceramic Sinktop with 8\" Widespread Faucet Hole in Biscuit",
      "finish": "Biscuit",
      "series": "Evin",
      "quantity": 5,
      "location": "R5A1: 5",
      "msrp": null,
      "salePrice": null,
      "discount": 65,
      "discountLabel": "65% off",
      "image": "assets/products/050-216632-8-b1.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model photo from 2020 folder"
    },
    {
      "row": 51,
      "code": "216632-8-CG-B",
      "name": "32\" Evin™ Ceramic Sinktop with 8\" Widespread Faucet Hole in Cool Gray",
      "finish": "Cool Gray",
      "series": "Evin",
      "quantity": 9,
      "location": "A4: 5; A5: 2; R5A1: 2",
      "msrp": null,
      "salePrice": null,
      "discount": 70,
      "discountLabel": "70% off",
      "image": "assets/products/051-216632-8-cg-b.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model photo from 2020 folder"
    },
    {
      "row": 52,
      "code": "216637-8-BI",
      "name": "37\" Evin™ Ceramic Sinktop with 8\" Widespread Faucet Hole in Bisciut",
      "finish": "Biscuit",
      "series": "Evin",
      "quantity": 5,
      "location": "A4: 2; R5A3: 1; R5A4: 2",
      "msrp": null,
      "salePrice": null,
      "discount": 65,
      "discountLabel": "65% off",
      "image": "assets/products/052-216637-8-bi.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model high-res catalog image"
    },
    {
      "row": 53,
      "code": "212231-1-CG",
      "name": "31\" Ceramic lav top w/integrated sink - fits 22\" depth cabinets (1 faucet hole)-Cool Gray",
      "finish": "Cool Gray",
      "series": "Kara",
      "quantity": 1,
      "location": "R5A5: 1",
      "msrp": 679.0,
      "salePrice": 305.55,
      "discount": 55,
      "discountLabel": "55% off",
      "image": "assets/products/053-212231-1-cg.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model photo from 2020 folder"
    },
    {
      "row": 54,
      "code": "212231-1-CG-A",
      "name": "31\" Kara™ Ceramic Sinktop with Single Faucet Hole in Cool Gray",
      "finish": "Cool Gray",
      "series": "Kara",
      "quantity": 10,
      "location": "A8: 6; R5A5: 4",
      "msrp": null,
      "salePrice": null,
      "discount": 70,
      "discountLabel": "70% off",
      "image": "assets/products/054-212231-1-cg-a.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model photo from 2020 folder"
    },
    {
      "row": 55,
      "code": "212231-8-WH",
      "name": "31\" Ceramic lav top w/integrated sink - fits 22\" depth cabinets (8\" widespread)-White",
      "finish": "White",
      "series": "212231",
      "quantity": 12,
      "location": "R5A6: 12",
      "msrp": 552.0,
      "salePrice": 110.4,
      "discount": 80,
      "discountLabel": "80% off",
      "image": "assets/products/055-212231-8-wh.jpg",
      "hasPhoto": true,
      "sourceNote": "2020 folder code match"
    },
    {
      "row": 56,
      "code": "212231-8-CG-B",
      "name": "212231",
      "finish": "Cool Gray",
      "series": "212231",
      "quantity": 1,
      "location": "R5A8: 1",
      "msrp": null,
      "salePrice": null,
      "discount": 50,
      "discountLabel": "50% off",
      "image": "assets/products/056-212231-8-cg-b.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model photo from 2020 folder"
    },
    {
      "row": 57,
      "code": "213325-1-WH",
      "name": "25\" Ashland™ Ceramic Utility Sinktop with Single Faucet Hole in White",
      "finish": "White",
      "series": "213325",
      "quantity": 6,
      "location": "R5A1: 6",
      "msrp": 803.0,
      "salePrice": 160.6,
      "discount": 80,
      "discountLabel": "80% off",
      "image": "assets/products/057-213325-1-wh.jpg",
      "hasPhoto": true,
      "sourceNote": "High-res catalog PDF image"
    },
    {
      "row": 58,
      "code": "215524-1-CG-B",
      "name": "215524",
      "finish": "Cool Gray",
      "series": "215524",
      "quantity": 3,
      "location": "R2A1: 3",
      "msrp": null,
      "salePrice": null,
      "discount": 60,
      "discountLabel": "60% off",
      "image": "assets/products/058-215524-1-cg-b.jpg",
      "hasPhoto": true,
      "sourceNote": "Same model photo from 2020 folder"
    },
    {
      "row": 59,
      "code": "E031137-E56",
      "name": "E031137",
      "finish": "American Walnut",
      "series": "E031137",
      "quantity": 2,
      "location": "R1A10: 2",
      "msrp": null,
      "salePrice": null,
      "discount": 50,
      "discountLabel": "50% off",
      "image": null,
      "hasPhoto": false,
      "sourceNote": "No photo yet"
    },
    {
      "row": 60,
      "code": "E47013-E23",
      "name": "E47013",
      "finish": "Glossy White",
      "series": "E47013",
      "quantity": 1,
      "location": "R1A7: 1",
      "msrp": null,
      "salePrice": null,
      "discount": 50,
      "discountLabel": "50% off",
      "image": null,
      "hasPhoto": false,
      "sourceNote": "No photo yet"
    },
    {
      "row": 61,
      "code": "E56111-W01",
      "name": "E56111",
      "finish": "White",
      "series": "E56111",
      "quantity": 1,
      "location": "R1A7: 1",
      "msrp": null,
      "salePrice": null,
      "discount": 50,
      "discountLabel": "50% off",
      "image": null,
      "hasPhoto": false,
      "sourceNote": "No photo yet"
    }
  ]
};
